server:
 port: 8080
 servlet:
  context-path: /API/v1



spring:
 application:
  name: career-day-service

 h2:
  console:
   enabled: true
   path: /h2-console

 jpa:
  show-sql: true


#Spring:
#  datasource:
#   username: root
#   password: Mentor94
#
#   url: jdbc:mysql://localhost:3306/career-day?autoReconnect=true&useSSL=false
#   testWhileIdle: true
#   initialization-mode: always
#
#   validationQuery: SELECT 1
#
#
#
#
#
#  # ===============================
#  # = JPA / HIBERNATE
#  # ===============================
#  jpa:
#   show_sql: true
#   format_sql: true
#   hibernate:
#    ddl-auto: update
#    naming:
#     strategy: org.hibernate.cfg.ImprovedNamingStrategy
#   properties:
#    hibernate:
#     dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#     enable_lazy_load_no_trans: true
#
#  # ===============================
#  # = Thymeleaf configurations
#  # ===============================
#  thymeleaf:
#   cache: false
#   mode: LEGACYHTML5
#   suffix: .html
#   prefix: classpath:/templates/
#   encoding: UTF-8

